version: '3.8'

services:
  app:
    build: .
    container_name: backend 
    ports:
      - "3000:3000"           
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev
    dns: ["8.8.8.8", "1.1.1.1"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}       
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
