name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Kodni klonlash
        uses: actions/checkout@v3

      - name: Docker image build qilish
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/online-course:latest .

      - name: DockerHub login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: DockerHub'ga push qilish
        run: docker push ${{ secrets.DOCKER_USERNAME }}/online-course:latest
